## 11-bluetooth.conf
## Supplemental configuration for system-wide bluetooth

monitor.bluez.properties = {
  bluez5.roles = [ a2dp_sink a2dp_source bap_sink bap_source hfp_hf hfp_ag ]
  bluez5.hfphsp-backend = native
}

monitor.bluez.rules = [
  {
    matches = [
      {
        ## This matches all bluetooth devices
        device.name = "~bluez_card.*"
      }
    ]
    actions = {
      update-props = {
        ## Ensure Bluetooth devices are always considered "available"
        bluez5.autoswitch-to-headset-profile = true
      }
    }
  }
]

## Re-enable device reservation for the root daemon. 
## The default main-systemwide profile disables it, but we need it for ALSA hardware.
wireplumber.profiles = {
  main-systemwide = {
    support.reserve-device = required
    monitor.alsa.reserve-device = required
  }
}
